// Where a number came from, as a display concept.
//
// Two axes already existed and were being confused with each other:
//   Channel — a business grouping (Meta Ads, Organic Search, Referral). Campaigns hang
//             off it, and Marketing already filters by it.
//   Source  — who WROTE the row: an integration id, 'demo' for the seeder, or nothing
//             at all for figures the app computes from its own tables.
//
// Only the Analytics page ever surfaced the second one, so on every other page there was
// no way to tell reported spend from invented spend. This module is that vocabulary.
//
// Deliberately import-free so client components can render a badge without dragging
// Prisma into the browser bundle — see tools/client-boundary.test.ts. That is also why
// the labels are duplicated here rather than read from lib/integrations/registry.ts,
// which imports the database. The ids are asserted against the registry by a test.

export type SourceTone = 'live' | 'seeded' | 'internal';

export type SourceMeta = {
  /** Short label for a badge. Kept to a word or two — these sit inside table cells. */
  label: string;
  /** Full name, for tooltips and the provenance line. */
  name: string;
  tone: SourceTone;
  hint: string;
};

/** Rows written by the seeder. Never real, and always labelled as such. */
export const DEMO_SOURCE = 'demo';

/** Figures the app derives from its own records rather than importing from anywhere. */
export const INTERNAL_SOURCE = 'internal';

const SOURCES: Record<string, SourceMeta> = {
  meta_ads: {
    label: 'Meta',
    name: 'Meta Ads',
    tone: 'live',
    hint: 'Reported by Meta Ads and refreshed on each sync.',
  },
  google_analytics: {
    label: 'GA4',
    name: 'Google Analytics 4',
    tone: 'live',
    hint: 'Reported by Google Analytics 4 and refreshed on each sync.',
  },
  semrush: {
    label: 'Semrush',
    name: 'Semrush',
    tone: 'live',
    hint: 'Reported by Semrush and refreshed on each sync.',
  },
  zoho_crm: {
    label: 'Zoho',
    name: 'Zoho CRM',
    tone: 'live',
    hint: 'Reported by Zoho CRM and refreshed on each sync.',
  },
  smartlead: {
    label: 'Smartlead',
    name: 'Smartlead',
    tone: 'live',
    hint: 'Reported by Smartlead and refreshed on each sync.',
  },
  meta_social: {
    label: 'Meta',
    name: 'Facebook & Instagram',
    tone: 'live',
    hint: 'Reported by the Facebook Page and Instagram Business APIs on each sync.',
  },
  google_search_console: {
    label: 'GSC',
    name: 'Google Search Console',
    tone: 'live',
    hint: 'Reported by Google Search Console and refreshed on each sync.',
  },
  google_ads: {
    label: 'Google Ads',
    name: 'Google Ads',
    tone: 'live',
    hint: 'Reported by Google Ads and refreshed on each sync.',
  },
  linkedin: {
    label: 'LinkedIn',
    name: 'LinkedIn',
    tone: 'live',
    hint: 'Reported by LinkedIn and refreshed on each sync.',
  },
  [DEMO_SOURCE]: {
    label: 'seeded',
    name: 'Seeded demo data',
    tone: 'seeded',
    hint: 'Generated by the seeder. Not a real figure — connect the platform to replace it.',
  },
  [INTERNAL_SOURCE]: {
    label: 'internal',
    name: 'Growth Center',
    tone: 'internal',
    hint: 'Computed from records in Growth Center itself, not imported from a platform.',
  },
};

/**
 * Null and unknown both resolve to 'internal' rather than throwing.
 *
 * A null source genuinely means "we made this number ourselves" — a lead count, a
 * pipeline total. An unknown one means a provider was added without a row here, and
 * showing it as internal is a better failure than a blank cell or a crash.
 */
export function sourceMeta(source: string | null | undefined): SourceMeta {
  if (!source) return SOURCES[INTERNAL_SOURCE];
  return SOURCES[source] ?? SOURCES[INTERNAL_SOURCE];
}

export const isLiveSource = (source: string | null | undefined) =>
  sourceMeta(source).tone === 'live';

export const isSeeded = (source: string | null | undefined) => source === DEMO_SOURCE;

/** Every id this module knows, for the filter dropdowns. */
export const KNOWN_SOURCES = Object.keys(SOURCES);
