import { NextResponse } from 'next/server';
import { hasDb } from '@/lib/prisma';
import { sendDigest } from '@/lib/digest';
import { generateInsights, growthContext } from '@/lib/ai';

/**
 * §20.6's daily run: the rules, then the digest. Scheduled in vercel.json.
 *
 * ── The rules had no schedule at all ─────────────────────────────────────────────────
 *
 * `generateInsights` was reachable only from the AI Insights page. The rules therefore ran
 * when somebody opened it and at no other time — so a critical finding was raised the
 * moment a person went looking, which is the moment they least needed telling. The
 * notification trigger and the health metrics were both built on top of that, and both
 * were measuring how often the page got opened.
 *
 * Running it here means the findings are current before anybody is told about them. It is
 * one model call a night, a fraction of a rupee, and the digest reads what it produced
 * rather than whatever was last generated by hand.
 *
 * ── Its own cron, not a tail on the sync ─────────────────────────────────────────────
 *
 * The sync runs at 01:30 and a digest sent then is read at nine anyway, with everything
 * else. More importantly a sync that runs long or fails would take the digest silently
 * with it, and the symptom of that is an email not arriving — which nobody notices.
 *
 * Authenticated the same way as the sync: CRON_SECRET as a bearer token, refusing to run
 * when the variable is unset rather than running openly. Sending mail from an open
 * endpoint is worse than syncing from one.
 */
export const maxDuration = 60;

function baseUrl(req: Request): string {
  // The configured URL first: on Vercel the request host for a cron invocation is the
  // deployment's own hostname, so a link built from it points at a specific immutable
  // deployment rather than at the app. It works, and it stops working when that
  // deployment is superseded.
  const configured = process.env.NEXTAUTH_URL || process.env.NEXT_PUBLIC_APP_URL;
  if (configured) return configured.replace(/\/$/, '');
  return new URL(req.url).origin;
}

export async function GET(req: Request) {
  const secret = process.env.CRON_SECRET;
  if (!secret) {
    return NextResponse.json({ error: 'CRON_SECRET is not set' }, { status: 503 });
  }
  if (req.headers.get('authorization') !== `Bearer ${secret}`) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
  }
  if (!hasDb()) {
    return NextResponse.json({ error: 'No database configured' }, { status: 503 });
  }

  // The rules first, so the digest reports today's findings rather than the last set
  // somebody's page visit happened to produce. A failure here must not stop the digest:
  // the findings already stored are still worth sending, and a model outage is not a
  // reason for the queue to go quiet.
  let generated: string | null = null;
  try {
    const { written, model } = await generateInsights(await growthContext(90));
    generated = `${written} findings via ${model}`;
  } catch (e) {
    generated = `failed: ${e instanceof Error ? e.message : 'unknown'}`;
    console.error('[cron/digest] insight generation failed:', e);
  }

  const result = await sendDigest(baseUrl(req));

  // Logged as well as returned. The response goes to the scheduler, which nobody reads
  // unless they already suspect something; a failed send has to be findable afterwards.
  if (result.errors.length) {
    console.error('[cron/digest] send failures:', JSON.stringify(result.errors));
  }

  return NextResponse.json({
    ok: result.errors.length === 0,
    generated,
    ...result,
  });
}
